### ISSUE TITLE
Mixing metadata type static and snmp

### ISSUE THREAD

**Issue by TvL2386** [akvorado/akvorado#1111]
Hi,

I've read the docs and looked through the issues and discussions to see if this has come up in the past, but I don't think it did.

I have a couple of exporters in my network that work great with akvorado. I now have an additional exporter that is outside of my network and control. This exporter is a commercial Anti-DDOS solution which sends us flowdata when traffic is routed through them. However, I'm not allowed to do snmp to their exporter ip. 

What I'm looking for is a possibility to have metadata type snmp by default and metadata type static for their exporter ip address. Because as I read, flows are dropped when interface information can't be determined.

I don't think it is possible with the current design.

**Comment by vincentbernat** [comment]
Yes, currently not possible, but shouldn't it too difficult to implement it.

**Comment by TvL2386** [comment]
That would be awesome! :-D

**Comment by vincentbernat** [comment]
Well, that's not that easy. I don't have an immediate solution that would fix this.
