### ISSUE TITLE
Support for Cisco ASA/NSEL

### ISSUE THREAD

**Issue by JordanBarnartt** [akvorado/akvorado#1156]
```
# akvorado version
akvorado v1.9.3
  Built with: go1.21.5
```

I'm trying to use Akvorado to parse NetFlows from a Cisco ASA device which uses NSEL (https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/asa_netflow.html).  It is able to correctly parse most information, including the post-NAT addresses, however, it treats   the amount of received packets as 0 for all flows.

From what I can tell, this is because, rather than use the NFV9_FIELD_IN_BYTES (1) and NFV9_FIELD_OUT_BYTES (23) fields, it uses the equivalent of the IPFIX_FIELD_initiatorOctets (231) and IPFIX_FIELD_responderOctets (232) fields.

To fix this, would it be a matter of changing https://github.com/akvorado/akvorado/blob/70caae1c85a2ecc9ee7e2036f06a14a7db864d54/inlet/flow/decoder/netflow/decode.go#L89 to include those two fields?

**Comment by vincentbernat** [comment]
Yes, add them on the same line. It will use the first non-zero one. If it works, you can do a PR.

**Comment by JordanBarnartt** [comment]
Yup, that seems to have done the trick.  I've submitted a PR: https://github.com/akvorado/akvorado/pull/1157

Thanks!

**Comment by vincentbernat** [comment]
Done in #1157.
