### ISSUE TITLE
Sampling rate parsing is broken

### ISSUE THREAD

**Issue by ytti** [akvorado/akvorado#1189]
https://github.com/akvorado/akvorado/blob/main/inlet/flow/decoder/netflow/decode.go#L49

````go
case netflow.NFV9_FIELD_SAMPLING_INTERVAL, netflow.NFV9_FIELD_FLOW_SAMPLER_RANDOM_INTERVAL, netflow.IPFIX_FIELD_samplingPacketInterval:
````

If we have sampling 1:500, then:
   IPFIX samplingInterval(34) is 500
and:
  IPFIX samplingPacketInterval(305) is 1
  IPFIX samplingPacketSpace(306) is 499 

Rationale is on the 2nd example is, that once we trigger sampling we can sample >1 packet. Use case could be cacheless sampling, where we fill export MTU, once we trigger export.
Nokia SROS uses the new codepoints (meaning results are 500x off), everyone else uses the old codepoint 34 (meaning rate is not recovered).

Further, technically you are condeering IPFIX+v9 codepoints both, regardless if declared format is IPFIX+v9, this works by chance, as there isn't over-lapping breaking difference, but this could change. However, there are releases, which will today use v9 codepoints, in IPFIX declared export, so making it correct will not necessarily make it work better.

**Comment by vincentbernat** [comment]
Thanks for the report. I'll fix that. As using IPFIX + Netflow v9 code points, they are backward compatible (for the standard ones), so it should be OK. Maybe it would be better to only rely on IPFIX codepoints in the code to make it clearer.

**Comment by vincentbernat** [comment]
I don't know why I added `netflow.IPFIX_FIELD_samplingPacketInterval`, but it was added in an unrelated change (in 2fe74ad43ac42973c662048c3bbfb312e5259618). I could just drop it if we expect 34 to always be present. From your descripton, I am unsure this is the case. Could you confirm?

**Comment by ytti** [comment]
Sorry for ambiguity. 

No, 34 is not always present. It is either 34 or (305,306) not both. 

Nokia SROS uses (305,306), everything else (to my knowledge) uses 34. 

But my chrystal ball says we will see more implementations to transition from 34 into (305,306), because ~everyone implements caching today, which is very very expensive to do, and it doesn't do anything anymore, sampled records are 1 packet deep, so cache is created at great cost, but never hit. And once this expensive cache is removed, it creates incentive to figure out how to ensure exported packets are as long as they were before, so that receiver PPS rate is unchanged, and this can be done, by increasing samplingPacketInterval to fill-up export packet with consecutive packets, to create statelessly as large export packet as required, while not-caching.

**Comment by vincentbernat** [comment]
I have pushed a fix. I already had a PCAP with only 305/306.

**Comment by ytti** [comment]
I believe you fixed this wrong:

```
samplingRate = packetInterval + packetSpace
```

Consider two cases 1:500 and 2:500, or (1,499 and 2,499)

Your sampling rate is 500 and 501. While you wanted 500 and 250.

So (packetInterval+packetSpace)/packetInterval, no?
