### ISSUE TITLE
Nexthop as a dimention

### ISSUE THREAD

**Issue by Rishi556** [akvorado/akvorado#1247]
Would it be possible to add nexthop as a dimension to the UI? I've got a router without BMP support and would still like to know the nexthop used with peers, and this can act as a workaround.

```
# akvorado version
akvorado v1.10.2
```

**Comment by vincentbernat** [comment]
This is already possible. You have to "enable" the `NextHop` column in your configuration. See https://demo.akvorado.net/docs/configuration#schema.
