### ISSUE TITLE
Flow Re-Sampling on Inlet

### ISSUE THREAD

**Issue by fischerdouglas** [akvorado/akvorado#1389]
There is some equipment that is not able to do sampling on Flow Exporting.

And with that, we have basically two options:

1. Applying a max rate on Flows per second on Inlet, what leads to imprecision on data.
2. Let it int and reach Kafka receiver and Click house, what explodes the needed CPU and Memory resources on core of Akvorado.

After it reaches Click house, we are able to sumarize the data a bit and reduce the use of disk.
But the CPU and memory were already spiked.

I was wondering if would be possible to creade some kind of re-sampling on inlet side.

Yes, I understand that it would consume some extra resources on Inlet.
But I imagine that it would be much-much lower than it is used on Click house.

My ideia would be something quite simple...
Just a simple ratio, without any advanced control of expiring timers and similar things.
But for now, this is just an idea.

Some considerations:
- Obviously, with a resampling, inlet will need to "tell" core that sampling is changed.
- I guess that excessive chances on resampling would be unhealthy for the environment, so it would be necessary to define what would be the min and max limits that would trigger the resampling.
- This resampling concours with max rate definitions in some way. A thing to be analyzed.
- In some way I guess that this idea/suggestion is related with the dynamic sampling rate that some Cisco devices can do.

By now, this is just an idea in the wind.
Thank you by comprehension until now.

**Comment by vincentbernat** [comment]
There is a `rate-limit` setting for flows: https://demo.akvorado.net/docs/configuration#flow. However note that I am currently introducing a new component, the outlet, and in the future the inlet will not decode flows, send them in Kafka and the outlet will decode them and push them to ClickHouse. Currently, I did not reimplement the rate-limit setting. It could be reimplemented in the outlet but it would mean that Kafka will get all the flows. Alternatively, we could drop packets at the UDP level (less precise).

**Comment by vincentbernat** [comment]
I am closing, since this feature exists today. I'll reopen when it disappears (except if I implement something in the meantime).
