### ISSUE TITLE
Pull Tenants For Prefix From Netbox or other IPAM

### ISSUE THREAD

**Issue by Rishi556** [akvorado/akvorado#1428]
It would be nice if we could use Netbox(or other IPAM) to pull tenant(and other) data to Akvorado.

Looking further the network sources might make it possible to do this, need to see if we can get Netbox to output in JSON format.

**Comment by vincentbernat** [comment]
You can use `network-sources` for that. See the example in `config/akvorado.yaml`.

**Comment by rinsekloek** [comment]
We use nautobot and I have done this by creating a script that fetches the Prefix data from Nautobot and exports it to a network-sources file:

The start of this is a GraphQL query:

query = """
query Prefixes{
  prefixes (status: "active"){
    prefix
    description
    family
    role { name }
    site { name, region { name } }
    tenant { name,group { name } }
  }
}
"""


After that you can do your filtering/to be sure you have proper data that matches your flow info.
