### ISSUE TITLE
Maxmind implementation not working

### ISSUE THREAD

**Issue by f0o** [akvorado/akvorado#1485]
```
# akvorado version
akvorado v1.11.2
  Built with: go1.23.2 X:loopvar

```

# Bug description

When using docker/docker-compose-maxmind.yml and with correct GEOIPUPDATE_ACCOUNT_ID and GEOIPUPDATE_LICENSE_KEY all flows are tagged with ASN 0 and Country is seemingly two null-bytes.

## Steps to reproduce the problem

**Akvorado version**: (first line of `akvorado version`)

0. Unset COMPOSE_FILE=${COMPOSE_FILE}:docker/docker-compose-ipinfo.yml
1. Set COMPOSE_FILE=${COMPOSE_FILE}:docker/docker-compose-maxmind.yml
2. Set GEOIPUPDATE_ACCOUNT_ID & GEOIPUPDATE_LICENSE_KEY
3. docker compose up -d
4. Feed flows
5. ???
6. Bug

## Expected outcome

Expected it not to be 0's ;)

## Current outcome

ASN is `0` and Country is what appears to be two null-bytes

**Comment by vincentbernat** [comment]
Can you check the logs of the geoip container? `docker compose logs geoip`

**Comment by f0o** [comment]
@vincentbernat 

```
geoip-1  | # STATE: Running geoipupdate
geoip-1  | # STATE: Sleeping for 48 hours
```

**Comment by vincentbernat** [comment]
Did you update the path to geoip files in `config/akvorado.yaml`?

**Comment by f0o** [comment]
🤦 

No... I feel really dumb now.

Closing as User-Error

**Comment by vincentbernat** [comment]
I have added a line about that in the `.env` file.

**Comment by f0o** [comment]
This isn't part of the issue but how does SrcGeoCity get populated?

I cant see a field `citydatabase` in the geoip block of `akvorado orchestrator --check --dump /etc/akvorado/akvorado.yaml`

**Comment by vincentbernat** [comment]
You need to change the database you retrieve. You can override `GEOIPUPDATE_EDITION_IDS` in your `.env` file.

**Comment by f0o** [comment]
I got the GeoLite2-City downloaded and appended `/usr/share/GeoIP/GeoLite2-City.mmdb` to the databases in the config/akvorado.yaml but no luck.

Do I need to replace Country.mmdb with CIty.mmdb instead of appending to the array?

**Comment by vincentbernat** [comment]
I think you can replace. City contains both countries and citites.

**Comment by vincentbernat** [comment]
> I have a quick question regarding this topic. Are we obliged to use 
> maxmind to get the cities or can it be done also with tthe basic ipinfo 
> included credentials?

No, the free database from ipinfo.io only contains the countries.

**Comment by BernieWillis** [comment]
Ah ok I was thinking that the fixed db may also contain those information as we can get it with a free account via curl:

curl ipinfo.io/212.27.48.10?token=xxxxxxxxxz
{
  "ip": "212.27.48.10",
  "hostname": "www.free.fr",
  "city": "Brie-Comte-Robert",
  "region": "Île-de-France",
  "country": "FR",
  "loc": "48.6925,2.6109",
  "org": "AS12322 Free SAS",
  "postal": "77170",
  "timezone": "Europe/Paris"
}

**Comment by abdullahdevrel** [comment]
Yeah, sorry. We only have the free country database that is integrated with Akvorado. I am not sure if our API service could be useful for this project because even with our generous 50k request per month limit for a flow processor like Akvorado, it will quickly get depleted, I think.

**Comment by BernieWillis** [comment]
Yeah right it is already great like this. If we want more then we will take a paid account. Thanks for the replies.
