### ISSUE TITLE
Akvorado drops sFlows with iface index 0x3F FF FF FF (= trafic originating from host and not forwarded)

### ISSUE THREAD

**Issue by ptnr** [akvorado/akvorado#153]
```
# akvorado version
akvorado v1.5.8
```

# Bug description

## Steps to reproduce the problem

Trying to monitor sFlows coming from debian servers (sFlow probe isn't on the upstream router but on 10+ servers in the same LAN). Using hsflow to generate sFlows directly on the debian hosts. 
When trafic originates/terminates at the host (and not forwarded - like a router), sFlow v5 specification says that the 0x3F FF FF FF/1073741823 value should be put in the inbound or oubound interface index field (the other interface field gets the correct interface index corresponding to the real WAN interface of the debian host).
(see this for reference https://sourceforge.net/p/host-sflow/feature-requests/4/)

To reproduce, simply install hsflowd https://sflow.net/downloads.php and use the "Host packet sampling on all NICs" config example here : https://sflow.net/host-sflow-linux-config.php
Then generate trafic on host, and quick Wireshark/tcpdump filtering sFlows will show the 0x3F FF FF FF or 1073741823 value in one of the interface index fields.

## Expected outcome

Akvorado should treat those sFlows by considering the 0x3F FF FF FF/1073741823 interface as "local", or originating/terminating directly on the host and should not drop the sFlow.

## Current outcome

Akvorado drops the sFlow because it tries to fetch interface data using SNMP. It succeeds fetching data for 1 of the 2 interfaces specified in the sFlow, the other interface being the 0x3F FF FF FF/1073741823 one. Akvorado then sends and SNMP query to gather data corresponding to the interface index 1073741823 which does not exist on the host (as it's a placeholder indicating the "local" host).
Host's SNMP daemon replies and error, causing Akvorado to drop the sFlow.

**Comment by vincentbernat** [comment]
Ack. Would you be able to write a patch for that?

**Comment by vincentbernat** [comment]
I have also implemented other cases: discarded traffic and multiple output interfaces.

**Comment by ptnr** [comment]
Oh wow that was quick, I originally planned to work on it today. Thanks a lot !
