### ISSUE TITLE
Show TCP Re transmits 

### ISSUE THREAD

**Issue by anthonyp-cns** [akvorado/akvorado#1566]
### Disclaimer

- [X] I have read and understood the disclaimer.
- [ ] I plan to implement the feature myself.

### Akvorado version

latest

### Feature description

Watching TCP Retransmits gives a good idea on the state of (particularly wireless) networks. I know its a field in netflow v9 and ipfix. However, it doesn't look like the value is natively stored in Clickhouse.

**Comment by vincentbernat** [comment]
Do you receive the value in your own flows?

**Comment by vincentbernat** [comment]
Yes, this is out of the scope. Flows are usually sampled and therefore, no such analysis can be done.
