### ISSUE TITLE
unable to query database

### ISSUE THREAD

**Issue by paunadeu** [akvorado/akvorado#172]
Hello,
Just upgrading from 1.5.x to 1.6.0, collector it's working fine, homepage too, but...  I see Unable to fetch data! Unable to query database. when I'm trying to visualize data.  I tried to do fresh install, but with same result.  I see in docker compose logs following error:

![image](https://user-images.githubusercontent.com/7139639/193474298-1c4af152-2a0f-4906-a764-968da07fd2be.png)

``` 
akvorado-akvorado-console-1          | {"level":"error","error":"code: 62, message: Syntax error: failed at position 877 ('INTERPOLATE') (line 16, col 2): INTERPOLATE (dimensions AS ['Other']))\n. Expected one of: token, DoubleColon, MOD, DIV, NOT, BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, IS, AND, OR, QuestionMark, alias, AS, Comma, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT","time":"2022-10-02T20:07:22Z","caller":"akvorado/console/graph.go:226","module":"akvorado/console","message":"unable to query database"}
```

```
root@akvorado:/opt/akvorado# docker compose exec -it akvorado-orchestrator akvorado version
akvorado v1.6.0
  Build date: 2022-09-30T16:20:15+0000
  Built with: go1.19.1
```

Available for more troubleshooting.

**Comment by vincentbernat** [comment]
You need to update ClickHouse. Check the version in `docker-compose`, you can update it to `22.8`.

**Comment by kostik2022** [comment]
I have same issue with Linux kernel 6. With kernel 5 - everything is ok.
Looks like this depends to some changes in networking (that docker uses)
