### ISSUE TITLE
SrcAS is my ASN instead of the actual ASN when using sflow from arista routers

### ISSUE THREAD

**Issue by alarig** [akvorado/akvorado#173]
Hello,

Following your presentation at the last FRnOG I’m testing akvodaro. Everything works fine, except that the SrcAS is wrong when the flow comes from an arista router. I checked the flow with wireshark and the SrcAS in it is right.
I’m using the last stable as of today: v1.6.0

I can provide .pcap and screenshot privately if needed.

Thanks for you work!

**Comment by vincentbernat** [comment]
Is there an AS path captured? It seems the logic in GoFlow2 differs if there is one. If there is one, it uses the AS field as source AS instead of SrcAS:

```go
			case sflow.ExtendedGateway:
				ipNh = recordData.NextHop
				flowMessage.NextHop = ipNh
				flowMessage.SrcAS = recordData.SrcAS
				if len(recordData.ASPath) > 0 {
					flowMessage.DstAS = recordData.ASPath[len(recordData.ASPath)-1]
					flowMessage.NextHopAS = recordData.ASPath[0]
					flowMessage.SrcAS = recordData.AS
				} else {
					flowMessage.DstAS = recordData.AS
				}
```

**Comment by alarig** [comment]
There is an AS path, but it’s weird to use `recordData.AS` as the source AS if there is one, because `recordData.AS` is the ASN of the router, while the source AS is `flowMessage.SrcAS`.

**Comment by vincentbernat** [comment]
Yes, I think this is a bug in GoFlow2. Also, the part setting DstAS to AS when no AS path is present is also problematic as we won't be able to fallback to other sources.

**Comment by alarig** [comment]
Thanks for the fix! Do you want me to make some tests?

**Comment by vincentbernat** [comment]
Yes, you can uncomment the `build:` option in `docker-compose.yml` in a recent checkout and run `docker-compose build akvorado-service`. This should provides you an easy way to test the result with your current setup.

**Comment by alarig** [comment]
It seems to work, the source ASN now looks correct :)
However, I have this in the logs:
```
akvorado_akvorado-exporter3_1 exited with code 1
akvorado_akvorado-exporter1_1 exited with code 1
akvorado-exporter2_1        | Error: received configuration file is not YAML (application/json; charset=utf-8)
```

But I still have the flows… So I don’t know if it breaks something or not.

**Comment by alarig** [comment]
Hum, very weird, I still have ~300 Mbps shown as my own ASN, but I’ll have to dig a bit more there, perhaps the issue is on the sflow it self

**Comment by alarig** [comment]
I catch one of those flows, the `AS Source` in wireshark is 0, so the fallback is intended, false alarm :)
I didn’t configure any fallback ASN lookup yet.

**Comment by vincentbernat** [comment]
Fallback ASN lookups won't fix that. We consider that if AS source is 0 in sFlow, it means this is the router AS because I suppose the associated route is not from BGP and is likely to be local. GoFlow2 (with the patch) will use the router AS and Akvorado itself won't try to look at fallback options.

**Comment by alarig** [comment]
Yeah, it’s what I meant. You can’t guess what’s the actual source ASN anyway.

That being said, I found what those `akvorado_akvorado-exporter3_1 exited with code 1` are for, it’s for the NetFlow ones. I don’t have any NetFlow anymore since the upgrade. Here is the full log:
```
kernel: br-d0fc2c22db31: port 2(vetha215065) entered forwarding state
docker-compose[13674]: akvorado-exporter0_1        | Error: received configuration file is not YAML (application/json; charset=utf-8)
docker-compose[13674]: akvorado-exporter0_1        | Error: unable to fetch configuration file: Get "http://akvorado-orchestrator:8080/api/v0/orchestrator/configuration/demo-exporter/0#0": dial tcp 172.18.0.2:8080: connect: connection refused
docker-compose[13674]: akvorado-exporter0_1        | Error: received configuration file is not YAML (application/json; charset=utf-8)
docker-compose[13674]: akvorado-exporter0_1        | Error: unable to fetch configuration file: Get "http://akvorado-orchestrator:8080/api/v0/orchestrator/configuration/demo-exporter/0#0": dial tcp: lookup akvorado-orchestrator on 127.0.0.11:53: no such host
docker-compose[13674]: akvorado-exporter0_1        | Error: received configuration file is not YAML (application/json; charset=utf-8)
```

There is still something listening to the NetFlow port:
```shell
host:~# netstat -lntpu | grep 2055
udp6       0      0 :::2055                 :::*                                21019/docker-proxy  
```

But even if I can telnet to the port on the logs, there is another problem because the outputed JSON prints an error:
```shell
host:~# telnet 172.18.0.2 8080
Trying 172.18.0.2...
Connected to 172.18.0.2.
Escape character is '^]'.
^]quit

telnet> quit
Connection closed.
host:~# curl --resolve akvorado-orchestrator:8080:172.18.0.2 'http://akvorado-orchestrator:8080/api/v0/orchestrator/configuration/demo-exporter/0#0'
{"message":"Configuration not found."}
```

**Comment by vincentbernat** [comment]
The exporters are for the demo. Just remove them from `docker-compose.yml` (I suppose you did remove them from `akvorado.yml`).
