### ISSUE TITLE
Support IPFIX from Juniper SRX

### ISSUE THREAD

**Issue by tim-preston** [akvorado/akvorado#191]
```
akvorado-1.6.1
```
I've been trying to throw IPFIX from a Juniper SRX at this and the flows get ingested but they do not get bytes or packets populated.

This looks like it's because the SRX does this a bit differently using:

- octetTotalCount (85)
- packetTotalCount (86)

rather than:

- octetDeltaCount (1)
- packetDeltaCount (2)

It would be great if the flow ingester would support this.

Sample pcap:
[pcap.zip](https://github.com/akvorado/akvorado/files/9788564/pcap.zip)

**Comment by vincentbernat** [comment]
[RFC 5102](https://www.rfc-editor.org/rfc/rfc5102.html) says:

```
[5.10.1](https://www.rfc-editor.org/rfc/rfc5102.html#section-5.10.1).  octetDeltaCount

   Description:
      The number of octets since the previous report (if any) in
      incoming packets for this Flow at the Observation Point.  The
      number of octets includes IP header(s) and IP payload.
   Abstract Data Type: unsigned64
   Data Type Semantics: deltaCounter
   ElementId: 1
   Status: current
   Units: octets
```

```
[5.10.4](https://www.rfc-editor.org/rfc/rfc5102.html#section-5.10.4).  octetTotalCount

   Description:
      The total number of octets in incoming packets for this Flow at
      the Observation Point since the Metering Process
      (re-)initialization for this Observation Point.  The number
      of octets includes IP header(s) and IP payload.
   Abstract Data Type: unsigned64
   Data Type Semantics: totalCounter
   ElementId: 85
   Status: current
   Units: octets
```

This is quite inconvenient. We cannot update old flows, so we need to compute the delta ourselves. This seems quite difficult to implement. Which version of JunOS are you running?

I even wonder if that's not just a bug. On your capture, if I use `(((cflow.dstport == 443) && (cflow.dstaddr == 193.123.47.66)) && (cflow.srcaddr == 77.101.40.116)) && (cflow.srcport == 9651)` as a filter, I see what looks like a single flow and the counters are not strictly increasing. So, it looks like Juniper is using `octetTotalCount` while it means `octetDeltaCount`.

**Comment by vincentbernat** [comment]
The same issue is raised here: https://github.com/robcowart/elastiflow/issues/646. It also says that's really a total, not a delta, so we cannot use them as is. A workaround seems to use Netflow v9 instead of IPFIX (replace `version-ipfix` by `version9`).
