### ISSUE TITLE
BGP BMP - Unknown route family 

### ISSUE THREAD

**Issue by fmcglinn** [akvorado/akvorado#215]
akvorado-1.6.1 - BMP session can not establish due to unknown route family.

Looks like the inlet service borks when it receives a l2vpn/vpls AFI, this causes the BMP session to never come up.

```
akvorado-inlet_1            | {"level":"info","exporter":"x.x.x.2","sysname":"xxx-cor2","time":"2022-10-20T01:01:26Z","caller":"akvorado/inlet/bmp/serve.go:160","module":"akvorado/inlet/bmp","message":"new connection"}
akvorado-inlet_1            | {"level":"error","exporter":"x.x.x.2","error":"unknown route family. AFI: 25, SAFI: 65","time":"2022-10-20T01:01:26Z","caller":"akvorado/inlet/bmp/serve.go:147","module":"akvorado/inlet/bmp","message":"cannot parse BMP body"}
```

**Comment by vincentbernat** [comment]
The route family has to be implemented in GoBGP. Can you share a pcap or a configuration snippet to be able to generate such a route?

**Comment by vincentbernat** [comment]
No need for the PCAP, I managed to configure a BGP session with VPLS NLRI. This is not trivial as it needs to be implemented in GoBGP: https://github.com/osrg/gobgp/issues/2590.

**Comment by fmcglinn** [comment]
Understood - thanks for checking this out. One would hope that gobgp can just write the BMP handling to be same as bgp neighbor where it only actually cares about locally supported AFI/SAFI combo's. 

Appreciate you looking into this! :)

**Comment by vincentbernat** [comment]
There is no easy way to skip the error. The BMP code is reusing the BGP code and the error happens outside the control of the BMP code.
