### ISSUE TITLE
Prefixes aggregation and filtering

### ISSUE THREAD

**Issue by hamshiva** [akvorado/akvorado#218]
### Discussed in https://github.com/akvorado/akvorado/discussions/217

<div type='discussions-op-text'>

<sup>Originally posted by **hamshiva** October 20, 2022</sup>
Hi,

I wonder if adding the possibility to use src and dst network prefixes as dimension and filter would be possible ?
I know that netflow gives srcMask and dstMask fields that could be used for that, but right now it seems that the inlet is not using those fields.

From my point of view this could be very useful for routing optimizations/decisions as obviously routing is done using network prefixes and not single addresses (/32 or /128).

What is your opinion about this ?
</div>

**Comment by JoachimOpdenakker** [comment]
Hi
I'd like to express my interest in this enhancement.
In our organization we'd also like to use akvorado for security analysis and it would be beneficial to use network prefixes for this.

**Comment by margau** [comment]
Hi,
I'm closely looking at the issue, as I have some use cases for this.
As far as I understand the current implementation in https://github.com/akvorado/akvorado/commit/689497aa13d13e8680ac4397f5b3bc53cdcba989, it is possible to see to which Prefix learned by BGP an flow belongs to (e.g. DstAddr 2001:db8::dead:beef with DstNetPrefix 2001:db8::/47 if that is in the RIS).

However, with the data format (only saving the Prefix Length, not the Prefix Network Address) it is not trivial to lookup the other way around.

My use case would be: Show all Interfaces/Devices which are sending traffic to the prefix 2001:db8::/47 learned from an BGP neighbor.
Maybe we could also add the base address (e.g. DstNetBase) of the prefix, which should make it trivial to filter that way around?

Thanks!

**Comment by vincentbernat** [comment]
You can use `<< 2001:db8::/47`, but it relies on the address, not the network. Is that enough? Currently, it is not possible to filter on the prefix length, but if it was, we could add `AND DstPrefixLen = 47` to get exactly what you propose.

**Comment by margau** [comment]
At least the first option would also include flows inside more specifics - but that would not be the case anymore with the `AND DstPrefixLen`, is that correct? 
So no more database changes are needed, only possibly a nicer filter UI automatically converting `DstNetPrefix = 2001:db8::/47` to `DstAddr << 2001:db8::/47 AND DstPrefixLen = 47`?
