### ISSUE TITLE
Support TLS encryption between Inlet and Kafka broker

### ISSUE THREAD

**Issue by fstolba** [akvorado/akvorado#277]
In order to better support distributed deployments Akvorado should be able to encrypt the channel between Inlet and the Kafka broker. 

This is probably just a matter of defining the relevant configuration knobs + passing them to the Kafka client library.

Configuration of the Kafka cluster itself is out of scope here - adding a "Kafka secure configuration" how-to to the docs would be a nice addition though.  

_Originally posted by @vincentbernat in https://github.com/akvorado/akvorado/discussions/58#discussioncomment-4226371_

**Comment by vincentbernat** [comment]
What do you require for authentication?
