### ISSUE TITLE
aggregate by subnet 

### ISSUE THREAD

**Issue by nitzan-tz** [akvorado/akvorado#279]
```
# akvorado version
akvorado 1.6.3
```
Can you add dimension of aggregate by subnet for SrcAddr and DstAddr (For both v4 and v6 ) so instead of showing /32, /128 akvorado will aggregate by /24 for example.
This way the user can identify how much each subnet is consuming and not a single address.
Nfdump/Nfsen have similar feature (srcip4/net ...)
https://manpages.ubuntu.com/manpages/trusty/man1/nfdump.1.html 

Nitzan

**Comment by vincentbernat** [comment]
That's #218.

**Comment by nitzan-tz** [comment]
Its very similar but if I understand correctly in #218 he suggest to use the flow field (srcMask ) for it and I suggest to use custom value for it

**Comment by vincentbernat** [comment]
Oh, yes, you are right, sorry.

**Comment by vincentbernat** [comment]
Wouldn't #218 solves your issue? Providing a custom value would be more difficult from an UI point of view (and just from the manual page of nfdump does not seem to say you can provide a custom value as well).

**Comment by nitzan-tz** [comment]
I prefer custom as some time the route information is not what you are looking for or you need higher aggerate to to see the actual distribution of traffic
BTW In nfdump it is custom. 
You can see how they build it in the nfsen UI in the following image but I agree it is more complicated 
![image](https://user-images.githubusercontent.com/7695109/204124177-0c305ca5-87c8-484b-a64c-5a3f4fbf8b9d.png)

**Comment by vincentbernat** [comment]
What would be easy is to add a few fixed values. /24, /16 for IPv4 for example.

**Comment by nitzan-tz** [comment]
It will be excellent too

**Comment by JoachimOpdenakker** [comment]
Agreed that also having an option to choose a fixed value would be a nice feature :)
