### ISSUE TITLE
Add Outbound Summary To The Home Screen

### ISSUE THREAD

**Issue by Rishi556** [akvorado/akvorado#352]
Currently the home screen(example can be viewed here https://demo.akvorado.net/) only has graphs summarizing incoming data, and below that, a ton of blank space as can be seen in the image below.

<center><img width="1053" alt="image" src="https://user-images.githubusercontent.com/10539109/209458850-16954eab-bc17-40ea-a492-b52037c1b3ed.png"></center>

Below the current inbound summary graphs, it would make sense to have the same graphs but for outbound. For content providers, outbound data is a lot more important than inbound and having that on the home screen would make the data more accessible.

It would also be useful(though not as important) to pick the ordering of the two, so the admins can choose what to have front and center.

**Comment by vincentbernat** [comment]
That's already configurable. See https://demo.akvorado.net/docs/configuration#console-service.
