### ISSUE TITLE
Problem in 1.6.4 with kafka health check

### ISSUE THREAD

**Issue by mat813** [akvorado/akvorado#368]
# Bug description

The kafka healthcheck was changed with the kafka update, and it now keeps being unhealthy. It now says `--bootstrap-server zookeeper:9092` but zookeeper does not listen on 9092. On the other hand, kafka does, I tried changing `zookeeper:9092` to `kafka:9092`, and now the container is shown as being healthy, but I don't know if it is the correct fix or if it is just being ignored.

## Steps to reproduce the problem

**Akvorado version**: akvorado v1.6.4

Run with the 1.6.4 docker-compose.yml

## Expected outcome

Kafka to be healthy.

## Current outcome

Kafka unhealthy.

**Comment by vincentbernat** [comment]
Yes, that's the right fix. Thanks.
