### ISSUE TITLE
Mikrotik (routerOS) send sample rate in little endian

### ISSUE THREAD

**Issue by drksbr** [akvorado/akvorado#417]
Hi, Vincent. 

I was using some equipment from other manufacturers and when testing with the Mikrotik I had difficulty determining the sample rate dynamically.

When researching about it in the GoFlow2 repository, I came across the following issue:

https://github.com/netsampler/goflow2/issues/113

What can we do to resolve this difficulty in akvorado?

**Comment by vincentbernat** [comment]
Can you confirm the endianess issue? Getting the sampling rate from the data instead of options should not be a problem, but the fact that it is not in network order is a bug that should be fixed on Mikrotik side.

**Comment by drksbr** [comment]
Yes. I have just confirmed that it is an endian fault in the field.

I agree with you that it's a Mikrotik problem, but can't we use some artifice to not depend on their solution? I believe it will take time or even never solve this problem.

**Comment by netzbus** [comment]
Hi,
I am also using a Mikrotik Router and having problems with the sampling rate. As suggested I am using "default-sampling-rate" in akvorado.yaml.
But the current flows in Akvorado differs tremendous compared with the flows in Mikrotik

**Comment by vincentbernat** [comment]
Yes, a solution is to use `default-sampling-rate`. I don't see another robust solution. Trying to guess endianess is difficult as if we read 65536, we can't really know if it's 256 or 65536.

**Comment by netzbus** [comment]
Any Ideas why Flows/s is not close at all to Mikrotik Active Flows?
![image](https://user-images.githubusercontent.com/11977124/215343079-123795d3-e654-4266-8720-16313a4ae90b.png)

**Comment by vincentbernat** [comment]
With IPFIX, active flows are not the ones that are sent, they are the one in the memory of the router and they are flushed when they are done or when a timeout happens.

**Comment by vincentbernat** [comment]
I'll close this issue as "won't fix". People should use `default-sampling-rate` or `override-sampling-rate`.

**Comment by vincentbernat** [comment]
As per https://github.com/pavel-odintsov/fastnetmon/issues/985, this seems to be fixed in recent versions of ROS. This should work with the next version of Akvorado.
