### ISSUE TITLE
Layer 3 sFlows ignored

### ISSUE THREAD

**Issue by ptnr** [akvorado/akvorado#493]
Using Akvorado 1.7.2, when a host using hsflowd (sflow agent that can be installed on debian), Akvorado ignores the source and destination IPs when trafic comes directly from/to the host itself (interface id 1073741823)

Here is a sFlow which has been retrieved by sflowtool on the akvorado instance (akvorado being shut down, sflowtool listening for incoming sFlows on 6343) (IPs have been anonymized to a /24) :

```
startSample ----------------------
sampleType_tag 0:1
sampleType FLOWSAMPLE
sampleSequenceNo 30466
sourceId 0:2
meanSkipCount 1
samplePool 30466
dropEvents 0
inputPort 2
outputPort 1073741823
flowBlock_tag 0:1
flowSampleType HEADER
headerProtocol 11
sampledPacketSize 70
strippedBytes 18
headerLen 52
headerBytes 45-00-00-34-DE-8A-40-00-40-06-5F-7E-45-3A-5C-6B-59-54-01-C2-92-92-00-50-2E-E6-15-46-8B-4C-24-38-80-10-60-00-FC-E1-00-00-01-01-08-0A-62-3D-3E-32-7A-B4-79-69
IPSize 52
ip.tot_len 52
srcIP 69.58.92.X
dstIP 89.84.1.X
IPProtocol 6
IPTOS 0
IPTTL 64
IPID 35550
TCPSrcPort 37522
TCPDstPort 80
TCPFlags 16
endSample   ----------------------
```

Here is the flow seen by Akvorado : 

```
curl http://127.0.0.1:8081/api/v0/inlet/flows\?limit=1
{
    "TimeReceived": 1676565184,
    "SamplingRate": 1,
    "ExporterAddress": "::ffff:172.19.64.X",
    "InIf": 2,
    "OutIf": 0,
    "SrcAddr": "",
    "DstAddr": "",
    "NextHop": "",
    "SrcAS": 0,
    "DstAS": 0,
    "GotASPath": false
}
```

SNMP polling works great, there are no errors reported by `curl -s http://127.0.0.1:8081/api/v0/inlet/metrics | grep '^akvorado_inlet' | grep _errors`, and Akvorado correctly handles every other sFlow (which are not linked to trafic originated from/directed to the host directly).

I cannot guarantee that this is an issue on the Akvorado, but by capturing the sflow on the Akvorado server I can ensure that IP addresses are correctly filled within the sFlow but ignored by Akvorado :( 

Have I missed something ?

Thanks a lot :)

-Pierre, Shadow

**Comment by vincentbernat** [comment]
I don't see anything in the code that would lead to that. Can you send me a pcap (mail if you want it to be anonymized) so that I check myself?

**Comment by ptnr** [comment]
Okay found it. When trafic comes to the host (from the internet), hsflowd sends sFlows with IP addresses AND MAC addresses embedded (and Akvorado accepts them).

When trafic comes from the host to the internet, hsflowd does not embed MAC addresses in sFlows samples. It's the only difference between a flow getting correctly parsed by Akvorado and a flow getting incorrectly parsed.

Fault isn't on the Akvorado side then, my bad. I will try to fix this on hsflowd side. Or if incoming flows lacking a MAC address could get a placeholder (00:00:00:00:00:00) so that they still get parsed, that'd be awesome. I'm looking at the code right now, but not a Go expert :(

**Comment by vincentbernat** [comment]
OK, I see, the sampled packet does not have an Ethernet header and it is currently not handled by Akvorado. This seems easy to fix.

**Comment by ptnr** [comment]
Searching through the code for how to fix this. I'm assuming it's located in the inlet component, am I right ?

**Comment by vincentbernat** [comment]
`inet/flow/decoder/sflow/decode.go`, search for `parseSampledHeader()`.

**Comment by ptnr** [comment]
I'm trying to implement the feature but I have issues compiling the repo :

```
root@akvorado:/home/pierre.tinard/akvorado# make
▶ building executable…
# akvorado/console/filter
console/filter/helpers.go:48:10: undefined: current
console/filter/helpers.go:65:10: undefined: current
console/filter/error.go:6:8: imported and not used: "fmt"
console/filter/error.go:10:17: undefined: errList
console/filter/error.go:38:17: undefined: errList
console/filter/error.go:59:17: undefined: errList
make: *** [Makefile:32: all] Error 2
```

I'm discovering go, so this may take a while. I'm willing to contribute, but if someone get the chance to implement this before I finish learning Go 101, that'd be awesome.

**Comment by vincentbernat** [comment]
Try make clean, it looks like your parser.go has been generated empty.

**Comment by vincentbernat** [comment]
I have pushed a fix for your issue.
