### ISSUE TITLE
The effect of the ipv6 filter on ipv4 aggregation

### ISSUE THREAD

**Issue by morhold** [akvorado/akvorado#534]
Firstly, thank you so much for Akvorado, it is convenient and very helpful in work.

I found a small problem when aggregating the network, the check was done on version 1.8.0 on demo.akvorado.net

If you select aggregation by /24 for ipv4, but leave /128 (by default) for ipv6, then output by /32 is also shown for ipv4, aggregation does not occur.

![image](https://user-images.githubusercontent.com/21057100/221770840-d2628301-9094-4982-b2d1-b08f07c6206b.png)

If you change the ipv6 filter to any other (for example /127), aggregation for ipv4 works.

![image](https://user-images.githubusercontent.com/21057100/221770888-ae6812a4-fa5a-416f-96cc-68fddc4445fd.png)

**Comment by vincentbernat** [comment]
Thanks, that should be fixed!
