### ISSUE TITLE
Clickhouse 23.4 LowCardinality

### ISSUE THREAD

**Issue by hamshiva** [akvorado/akvorado#669]
Hi,

Running Akvorado 1.8.3 with Clickhouse 23.4 is giving me some troubles.

# Bug description
Akvorado is unable to create the Clickhouse flows tables.

## Steps to reproduce the problem

**Akvorado version**:
akvorado v1.8.3
  Build date: 2023-04-28T17:01:57+0000
  Built with: go1.20.3

Run Akvorado orchestrator with an empty Clickhouse (23.4.1.1943 from https://packages.clickhouse.com/deb) database

## Expected outcome
Akvorado creates the needed tables.

## Current outcome

```
May 02 15:55:51 localhost akvorado[869049]: {"level":"error","error":"cannot create raw flows table: code: 455, message: Creating columns of type LowCardinality(IPv6) is prohibited by default due to expected negative impact on performance. It can be enabled with the \"allow_suspicious_low_cardinality_types\" setting.","time":"2023-05-02T15:55:51Z","caller":"akvorado/orchestrator/clickhouse/root.go:89","module":"akvorado/orchestrator/clickhouse","message":"database migration error"}
```

**Comment by vincentbernat** [comment]
You can workaround the issue by using v22.8 which is an LTS version.

**Comment by hamshiva** [comment]
Hi @vincentbernat, this is exactly what I'am doing :)

Still the issue exists for those who would like/need to use newer release of Clickhouse.

Regards,

**Comment by vincentbernat** [comment]
This is fixed in https://github.com/akvorado/akvorado/commit/6244b2e13627206becf20e93a63e5d0df0c16594.
