### ISSUE TITLE
IPFIX parsing issue

### ISSUE THREAD

**Issue by hamshiva** [akvorado/akvorado#671]
# Bug description
It seems that the inlet do not parse packets correctly as flows look very skinny and do not end up in the database.

I use Juniper ipfix configuration. It is working correctly with Akvorado 1.6.4 but not with 1.8.0-1.8.4. I could not test earlier version as I need snmp agents map on this new installation and could not get it working correctly with 1.7.x releases.
I redacted IPs for confidentiality issue.

I followed the troobleshooting steps, inlet do not shows any errors after a few seconds running and the forwarded flows counter increase correctly.
The source router is the same on both installations.

## Steps to reproduce the problem

**Akvorado version**: 
```
# akvorado version
akvorado v1.8.3
  Build date: 2023-04-28T17:01:57+0000
  Built with: go1.20.3
```
Follow the configuration for Juniper https://demo.akvorado.net/docs/operations#juniper excepts that I use IPfix instead of netflow v9:
```
set services flow-monitoring version-ipfix template ipv4 flow-active-timeout 60
set services flow-monitoring version-ipfix template ipv4 flow-inactive-timeout 60
set services flow-monitoring version-ipfix template ipv4 template-refresh-rate seconds 30
set services flow-monitoring version-ipfix template ipv4 option-refresh-rate seconds 30
set services flow-monitoring version-ipfix template ipv4 ipv4-template
set forwarding-options sampling instance ipfix family inet output flow-server xx.xx.xx.xx version-ipfix template ipv4
```
I use the default configuration file provided by ```akvorado orchestrator -CD /dev/null``` except for: 

- the listen ports that I changed for inlet and console
- the classification rules:
```
      exporterclassifiers:
        - ClassifySiteRegex(Exporter.Name, "^([^-]+)-([^-]+)-([^-]+)", "$3")
        - ClassifyRole("edge")
      interfaceclassifiers: 
        - |
          ClassifyConnectivityRegex(Interface.Description, "^(SUB|TRANSIT|PNI|PEERING):? ", "$1") &&
          ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
          ClassifyExternal()
        - ClassifyInternal()
 ```
- the snmp agents map (that I use to poll the router on its management interface)

## Expected outcome
On my other Akvorado install (1.6.4) the result looks like this and is working correctly:
```
curl http://localhost:8083/api/v0/inlet/flows\?limit=1
{
    "TimeReceived": 1683039942,
    "SequenceNum": 197656203,
    "SamplingRate": 1000,
    "FlowDirection": 255,
    "ExporterName": "somefqdn",
    "ExporterRole": "edge",
    "ExporterSite": "dc3",
    "TimeFlowStart": 1683039881,
    "TimeFlowEnd": 1683039881,
    "Bytes": 1097,
    "Packets": 1,
    "Etype": 2048,
    "Proto": 6,
    "SrcPort": 39392,
    "DstPort": 80,
    "InIf": 605,
    "OutIf": 721,
    "IPTTL": 60,
    "TCPFlags": 24,
    "SrcAS": AAAAA,
    "DstAS": BBBBBB,
    "SrcNetMask": 31,
    "DstNetMask": 23,
    "NextHop": "AAAAAAAAAAAAAP//BSrFAQ==",
    "SrcCountry": "FR",
    "DstCountry": "FR",
    "InIfName": "ae2.0",
    "OutIfName": "ae3.0",
    "InIfDescription": "CORE: link",
    "OutIfDescription": "SUB: to-dest",
    "InIfSpeed": 20000,
    "OutIfSpeed": 20000,
    "OutIfConnectivity": "sub",
    "OutIfProvider": "to-dest",
    "SrcAddr": "xx.xx.92.249",
    "DstAddr": "xx.xx.106.66",
    "ExporterAddress": "xx.xx.176.6",
    "InIfBoundary": "INTERNAL",
    "OutIfBoundary": "EXTERNAL"
```

## Current outcome

```
curl http://localhost:8083/api/v0/inlet/flows\?limit=1
{
    "TimeReceived": 1683104294,
    "SamplingRate": 1000,
    "ExporterAddress": "::ffff:xx.xx.176.6",
    "InIf": 603,
    "OutIf": 712,
    "SrcVlan": 0,
    "DstVlan": 0,
    "SrcAddr": "::ffff:78.xx.xx.97",
    "DstAddr": "::ffff:92.xx.xx.44",
    "NextHop": "::ffff:37.xx.xx.24",
    "SrcAS": 65200,
    "DstAS": AAAAA,
    "GotASPath": false
```

**Comment by hamshiva** [comment]
I just tried to upgrade Akvorado on my currently working installation from 1.6.4 to 1.7.0 and I have the same issue.
Thus this is something that was introduced between thos 2 versions.

Regards,

**Comment by vincentbernat** [comment]
The fact that flows reported by the API endpoint are smaller is expected. Are the IP addresses correct? You redact them in a different way, so are they mangled?

**Comment by hamshiva** [comment]
The IP addresses are correct. But nothing arrive into the DB...

How can I check that the flows are correctly decoded and enriched ?

Regards,

**Comment by hamshiva** [comment]
Ok, I found the culprit. The issue was my clickhouse server configuration.
This is not a bug then.
Sorry for the inconvenience.
