### ISSUE TITLE
gNMI for flow enrichment

### ISSUE THREAD

**Issue by hellt** [akvorado/akvorado#759]
Hi @vincentbernat and the rest of the Akvorado team,

It is 2023 and maybe it is time to make a beautiful Akvorado even more awesome by adding modern data retrieval protocols such as Openconfig's [gNMI](https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md)?

This will help bring more DC fabrics to enjoy Akvorado, as some of them started to switch to gNMI from SNMP.

We can use [openconfig/gnmic](https://gnmic.openconfig.net/) API to integrate it nicely into the Go codebase of Akvorado, and it should be rather a straightforward thing to do.

Looking forward to hear your thoughts on that, collaborate and bringing the future closer to Akvorado enrichers.

/cc @karimra @jbemmel

**Comment by protonjhow** [comment]
To add some colour here, I enjoyed Will's talk at SwiNOG, and was playing around with Akvorado in our Lab. It's certainly more approachable than our goflow/pipeline/clickhouse adventures to date. For that, I am hugely appreciative of the work to date.

At Proton we require "secured" transport for telemetry and signalling wherever possible and whilst Akvorado supports SNMPv3, Nokia SR-L for example, does not. In fairness, the gNMI telemetry they offer is miles better so I don't miss SNMP... except for edge cases like this.

My Go skills are minimal, but I am happy to chip in if I can, obviously test and provide usable feedback to smarter people than me to move this forward as well. ;)

**Comment by vincentbernat** [comment]
The SNMP part was made modular last month, so it's easier now than it was before.

**Comment by vincentbernat** [comment]
First question to implement that: should we use "Get", "Subscribe" or have a configuration on the exporter side on what to push?

**Comment by hellt** [comment]
You can use a simple Get given that retrieved amount data is not huge

**Comment by vincentbernat** [comment]
A few followup questions:
- does the library handles reconnect automatically?
- should encoding be user configurable? what the default should be?

**Comment by karimra** [comment]
> * does the library handles reconnect automatically?

Yes.

> * should encoding be user configurable? what the default should be?

Yes, not all routers support the same set of encodings, the default per the gNMI spec is JSON (ENUM value=0)

There is a Get RPC example [here](https://github.com/openconfig/gnmic/blob/main/examples/pkg/get_rpc/main.go)

**Comment by jbemmel** [comment]
Encoding could be automatically selected based on capability discovery
response

**Comment by vincentbernat** [comment]
Trying on XRv, capabilities say:
```
supported encodings:
  - JSON_IETF
  - ASCII
  - PROTO
```

However, `-e proto` says:

```
target "127.0.0.1:10371" get request failed: "127.0.0.1:10371" GetRequest failed: rpc error: code = Unimplemented desc = gNMI: unsupported get-request encoding: PROTO
```

and `-e ascii` says:

```
[
  {
    "source": "127.0.0.1:10371",
    "timestamp": 1690060169927101520,
    "time": "2023-07-22T21:09:29.92710152Z",
    "updates": [
      {
        "Path": "interfaces",
        "values": {
          "interfaces": "\n"
        }
      }
    ]
  }
]
```

So, detection from capabilities does not look great...

I think I will implement gNMI using subscribe. This enables to have up-to-date information all the time.

**Comment by karimra** [comment]
Not all devices are "good" in what they report on capabilities RPC.
Sometimes certain encodings of that list are supported only with some RPCs or only with certains paths.

I think It's worth implementing both get and subscribe. To not use a subscription slot if the device has some resource limitation. But this can be left out for later as an enhancement.

**Comment by vincentbernat** [comment]
Getting the speed of an interface is quite painful with OpenConfig (constant for each speed for Ethernet device, specific field for LAGG, I don't know what else for others). Can I assume that `ietf-interfaces` is implemented by almost everyone and use that instead? Also, for subscribe, can I assume that devices will send the initial state as well in streaming mode as well when not setting the "updates only" flag?

Maybe testing on XRv is an error as the behavior is quite erratic.

**Comment by hellt** [comment]
In my opinion we should rather consider vendor' models instead of OpenConfig. OC might not be available on certain platform, nor it might be enabled on some by default.
Better stick with vendor's yang models instead.

`ietf-interfaces` is not implemented on many vendors, I can think of Arista and Nokia as prime examples, pretty sure Juniper doesn't expose ietf as a standalone set of models either.


Since vendor's yang is, of course, not common across all platforms I see two ways this can be achieved:

1. Akvorado makes paths configurable for stats it requires. Users of certain platforms provide the path templates which akvorado uses to subscribe (along with the encoding).
2. Akvorado embeds those paths templates for a selected list of most common platforms in its code, while still making this a configurable option in case the path template is not working for whatever reason.

**Comment by vincentbernat** [comment]
Honestly, this is a bit a mess and I fear the amount of support I will have to provide if I add gNMI support.

I have tried the JunOS implementation. It seems they are unable to use GET at all (it complains about missing path). Subscribing with an incorrect encoding (like `json_ietf` which is in capabilities) just returns no result, you need to use mode once to get the error about the encoding (and use `json` or `proto`, neither are parts of the capabilities). The capabilities mention a `junos-state-interfaces` which does not look distributed in [their repository](https://github.com/Juniper/yang/tree/c2dfe1caf5599af8ba5d76d1dbf9833340390dbc/21.4/21.4R1/junos).

Also, it seems Juniper does not care much about the origin. If I use `ietf-interfaces:/interfaces/interface[name=ge-0/0/1]`, I don't get anything that looks like the model, including attributes named `state/parent-ae-name`, while on XRv, I get nothing. Cisco does not seem to have anything other than IETF and OC for interfaces, so no clue on how to get the speed.

**Comment by hellt** [comment]
I'd say it is not absolutely necessary to land in all vendors with gNMI support on day 1. Let gNMI offenders catch up first, before adding them to the pack.
What I think is more important is to get gNMI integrated with akvorado backend. You can try SR Linux or SR OS which I can help with to test the integration.

As for the support, as an akvorado users I'd be absolutely fine by taking on responsibility of providing the encoding and paths via configuration, rather than expecting akvorado maintain it. This should take off the burden from the maintainers.

**Comment by vincentbernat** [comment]
What would you suggest I subscribe to to get system name, interface index, name, description and current speed on SR Linux? A gnmic example command-line would help for me to be totally sure to understand how origin should be written.

Also:
1. If I subscribe with the wrong encoding, I should get an error? I could try to subscribe with `proto`, `json` or `json_ietf`, whatever first succeeds.
2. If I subscribe to something that does not exist, should it error or be ignored? Depending on the case, I suppose I could cover most cases.
3. Can I rely on the fact that when subscribing, I will receive the initial state, followed by the sync update message?

It would help to get "yes", "ignored" (but error would work too), "yes".

**Comment by karimra** [comment]
```shell
gnmic -a $address -u $username -p $password --skip-verify \
sub \
-e ascii \
--stream-mode sample \
--sample-interval 10s \
--path /system/name/host-name \
--path /interface/if-index \
--path /interface/description \
--path /interface/ethernet/port-speed
```

1. Yes.
2. You will get an error if a path does not exist in the schema, but you won't get an error if the path is valid but the object it points to was not configured yet (e.g a YANG list)
3. Yes (I don't know of any device that currently honors the updates-only attribute)

**Comment by vincentbernat** [comment]
`port-speed` will not work for non-Ethernet interface. I suppose I could add lagg-speed to the list.

**Comment by protonjhow** [comment]
On the support topic, I thing making it a user requirement, with best effort doc for the content per vendor and leave the community to updat docs if it changes? I’d be ok with that and as a Nokia and Juniper person with recent experience with OC, I know the pain  Sent from Proton Mail for iOS On Sun, Jul 23, 2023 at 20:00, Vincent Bernat ***@***.***> wrote:  
port-speed will not work for non-Ethernet interface. I suppose I could add lagg-speed to the list.

**Comment by vincentbernat** [comment]
@karimra any down side on using the "onchange" mode instead of the sample mode?

**Comment by karimra** [comment]
I don't see any except support on the device side. Certain devices don't support on-change for all paths.

**Comment by vincentbernat** [comment]
@karimra I am sorry, but I still fail to extract any information. I have a 7750 SR running 22.10 with gRPC enabled:

```
gNMI version: 0.7.0
supported models:
  - nokia-conf, Nokia, 22.10.R3
  - nokia-state, Nokia, 22.10.R3
  - nokia-li-state, Nokia, 22.10.R3
supported encodings:
  - JSON
  - BYTES
  - PROTO
  - JSON_IETF
```

In the configuration:

```
A:admin@bznlab-sr1-1# info configure system management-interface yang-modules
    nokia-submodules false
    nokia-combined-modules true
```

But I have two paths available: `/state` and `configure`. None of your paths returns something. As they are not openconfig path either, I wonder on which platform they would work?

**Comment by hellt** [comment]
You asked about SR Linux originally, these paths are valid for srlinux, not sros

**Comment by karimra** [comment]
They are for SRLinux

**Comment by karimra** [comment]
For sros try:
`/configure/system/name`, `/configure/port/description`, `/configure/router/interface/description` , `/state/router/interface/if-index`, `/state/port/ethernet/oper-speed`

**Comment by vincentbernat** [comment]
Another stupid question: gNMI spec says it's better to specify origin. I am confused on how to find origin. For OpenConfig, this is `openconfig`, but for everything else? It seems YANG does not have the concept of origin (only namespace). Whatever origin I specify, I am able to get the same results.

**Comment by hellt** [comment]
@vincentbernat until vendor implementation reach gnmi 0.10.0+ you can't derive the native origin. So I'd say leave it empty, for all implementations this will mean use native origin, until explicitly overridden via config.

**Comment by vincentbernat** [comment]
For the fallback to openconfig, do I keep `openconfig:`?

**Comment by hellt** [comment]
Yes, 'openconfig' origin is the right one for that oc

**Comment by vincentbernat** [comment]
I am using `GetResponseToEventMsgs()` (is that a good choice?), but I am unsure what I should expect for values. Depending on the encoding, I could get different paths (`/system/openconfig-system:config/hostname`,  `/system/config/hostname`). Maybe there is something to normalize them (I don't care about getting the namespaces). As I get a `map[string]interface{}`, what should I expect `interface{}` to be if encoding is set to `proto`?

**Comment by karimra** [comment]
That would depend on what the router sends as typedValue when the encoding is set to proto. Note that not all routers support that encoding with the Get RPC. I would suggest using json or json_ietf. 

The values are built by this function `func getValueFlat(prefix string, updValue *gnmi.TypedValue) (map[string]interface{}, error) `

**Comment by vincentbernat** [comment]
I am still making baby steps on implementing this. I am looking at [gRPC Network Management Interface (gNMI)](https://www.openconfig.net/docs/gnmi/gnmi-specification/). For `Get()`, it says that if any path exists but is not found, it will return `NOT_FOUND` (3.3.4).  This is highly inconvenient. It means we cannot bundle several `Get()` requests inside a single API call (something SNMP is able to do since SNMPv2).

However, for subscribe, it is explicitly said that a path may not exist yet and it should not be a problem (3.5.1.3). For a bit of context, I am using https://github.com/google/gnxi/blob/master/gnmi/server.go to be able to get unit tests. And it makes the RPC fails if any path does not exist on Subscribe.

Moreover, this implementation does not seem to return results for paths without keys, for example with `openconfig:/interfaces/interface/state/ifindex`, I get (when using `tg.SubscribeOnce()`):

```
rpc error: code = NotFound desc = path origin:"openconfig"  elem:{name:"interfaces"}  elem:{name:"interface"}  elem:{name:"state"}  elem:{name:"ifindex"} not found: rpc error: code = NotFound desc = schema key name is not found in gNMI path origin:"openconfig"  elem:{name:"interface"}  elem:{name:"state"}  elem:{name:"ifindex"}, root map[string]*model.OpenconfigInterfaces_Interfaces_Interface
```

If I specify `openconfig:/interfaces/interface[name=GigabitEthernet1/10]/state/ifindex`, it works fine. The spec does not seem to say anything about unkeyed paths and none of the examples show an unkeyed path. Are the keys mandatory? Or is it a limitation of gnxi server?

**Comment by hellt** [comment]
If you're looking for a reference gnmi implementation I think lemming is the newer google initiative 
https://github.com/openconfig/lemming

**Comment by vincentbernat** [comment]
Thanks. It's a big piece of code, I need to investigate how to run a minimal gNMI server from that.

As for unkeyed paths, it seems it works with gxni implementation if I use wildcards (`openconfig:/interfaces/interface[name=*]/state/ifindex`).

**Comment by hellt** [comment]
You can also run srlinux in GH actions if you can go beyond unit testing (and still get coverage report)

**Comment by vincentbernat** [comment]
As for Lemming, it seems the implementation is still incomplete:

```
 08:42 ❱ gnmic --insecure  -a 100.107.255.2:9339 --encoding json_ietf sub --path openconfig:/interfaces/interface  --mode once
rpc error: code = InvalidArgument desc = request must contain a prefix &gnmi.SubscribeRequest{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(0xc0002a2b88)}, sizeCache:0, unknownFields:[]uint8(nil), Request:(*gnmi.SubscribeRequest_Subscribe)(0xc005fe63f8), Extension:[]*gnmi_ext.Extension(nil)}
Error: one or more requests failed
```

Adding a `--prefix` flag would lead to Lemming complains about a missing target that should be set to `fakedut`. It seems to be defined in 2.2.2.1 and optional. Again, this makes me wonder if I will cross implementations in the wild requiring a prefix and a target for some reason.

As for using srlinux for testing, it could be an option. However, relying on a proprietary component (even just for testing) is not ideal. I didn't find the documentation on how to have a kind of ZTP without involving a lot of moving pieces. It seems containerlab is mounting a topology file and a configuration file but is also executing commands after the container started. Is it possible to have something functional with just mounting files inside the container?

**Comment by hellt** [comment]
I haven't tried Lemming myself, but both prefix and target are optional, so either there is a config knob that makes them mandatory that lemming sets for some use case, or they have these defaults for some specific case. If time permits you can raise a question against their repo.

You can start srlinux container without containerlab indeed, I just updated the instructions [here](https://learn.srlinux.dev/get-started/#docker-cli), but until march next year you won't be able to use openconfig using the unlicensed container image we offer.

But just in case, once you start the container with the mounted config, you can use gnmic:

```
gnmic -a 172.17.0.4 -u admin -p 'NokiaSrl1!' --skip-verify -e json_ietf get --path /interface/description
```

**Comment by vincentbernat** [comment]
I don't mind using SRLinux vendor modules. Where can I grab `srl23-7-1.json`?

**Comment by hellt** [comment]
it is linked under that + sign next to the line with mount
https://gist.github.com/hellt/3f695394d705ed2bf016f7919ba90018

**Comment by netixx** [comment]
> You can use a simple Get given that retrieved amount data is not huge

I would go for subscribe, since we could continuously update the data as it changes (ideally with an ON_CHANGE subscription, but SAMPLE polling should work also). Like when an interface is renamed for example.

In a next step, it could open the road for routing enrichment using GNMI as well (subscribe on RIB paths), instead of BMP. Plus side of this is that only the instance receiving the flow would need to subscribe to the target.

**Comment by vincentbernat** [comment]
Hey! Moving forward again in implementing gNMI support, even if I regularly shake my head on how under-specified gNMI is.

Another question for experts: what is the most stable way to parse the output of a subscribe call? It seems there is some variations depending on the implementation of the server part, notably on how results are grouped or if a prefix is returned or not. It may also depends on the encoding. Ideally, I should parse the results independently from the encoding. I can use `github.com/openconfig/gnmic/pkg/formatters` or not depending on what is more future-proof.

As an example, I actually use this piece of code where I try to merge stuff to erase the differences between implementations:

```go
			got := map[string]interface{}{}
			for _, resp := range subscribeResp {
				events, err := formatters.ResponseToEventMsgs("hello", resp, nil)
				if err != nil {
					t.Fatalf("ResponseToEventMsgs() error:\n%+v", err)
				}

				// Merge everything
				for _, ev := range events {
					for k, v := range ev.Values {
						got[k] = v
					}
				}
			}
```

**Comment by karimra** [comment]
With that piece of code you are loosing the tags of each event message. The tags are some metadata labels about where the msg comes but more importantly the keys contained in the paths.
`formatters.ResponseToEventMsgs()` converts each gNMI notification in a subscribe response to an event msg (detailed [here](https://gnmic.openconfig.net/user_guide/event_processors/intro/#the-event-format))

As an example:
The response (prototext)
```
update:  {
  timestamp:  1704329230323851457
  update:  {
    path:  {
      elem:  {
        name:  "interface"
        key:  {
          key:  "name"
          value:  "ethernet-1/1"
        }
      }
      elem:  {
        name:  "admin-state"
      }
    }
    val:  {
      string_val:  "enable"
    }
  }
}
```

becomes (event)

```json
[
  {
    "name": "default-1704329273",
    "timestamp": 1704329273367334006,
    "tags": {
      "interface_name": "ethernet-1/1",
      "source": "clab-ex-srl1",
      "subscription-name": "default-1704329273"
    },
    "values": {
      "/interface/admin-state": "enable"
    }
  }
]
```

**Comment by vincentbernat** [comment]
Thanks! My point was more about how to have something that would work with "any" encoding (at least `json` and `json_ietf`) and any implementation. For example, when using `json_ietf`, the paths are namespaced. The "event" format does not delete all the differences.

**Comment by vincentbernat** [comment]
I made some progress in gNMI support, but this is quite difficult. My current observations when testing with SR Linux:

- Streaming + on change does not transmit delete events. Also, from my understanding, I should expect some implementations unable to send some events (notably, OpenConfig says what can and what can't send on change events). So, not using this.
- Streaming + sampling: no way to get delete events either, so I would need to handle expiration of data on my side. I settled to use once mode to avoid having too much complexity.
- I need to index interfaces using their ifindex (that's what used in the flows). However, I have no strong guarantee than the keys used for the ifindex path will match for description or speed. I assumed that for description, they should match, and for speed, I can try to find the speed by looking for the speed of the upper interface by looking at a prefix of the key. This wouldn't work if stuff was indexed by some kind of index instead.
- I cannot subscribe to `/interface/name`. I know the name is also present as a key, but this is another complexity to handle. For a subinterface, I can use `/interface/subinterface/name`, but not for a regular interface. Also, what would happen for an interface without a description and no speed? I won't know it exists.
- A similar difficulty is that when values are JSON encoded, an implementation could totally send the content of `/interface` as a JSON blob using JSON IETF encoding. This would mean keys have to be guessed as they are not part of the metadata anymore but part of the value. As this does not seem to be implemented by gnmic either, I suppose there is no implementation in the wild doing that.

My current conclusion is gNMI may be good if the end user is directly collecting data for its own use and can just apply the needed tweaks for each platform, but when building something that should work with little configuration, this is quite difficult. If I hadn't poured so many week-ends trying to implement something, I would have given up. I am trying not to think of the various implementation bugs I will get when trying something else than SR Linux.

**Comment by jbemmel** [comment]
@vincentbernat you are correct that this would be very brittle. You would need to look at different gNMI implementations and come up with a 'lowest common denominator'

Specifically for SR Linux our team may be able to work with you on some of the limitations (@hellt mentioned looking into DELETE events iirc for example?) but this will always be cutting edge, with many caveats

**Comment by vincentbernat** [comment]
While some of the pain points may be improved with SR Linux, I have to support the other less accessible vendors. I made some progress today in #1043 and hopefully, I am near the end and I think this looks good. I'll add some metrics and this should be OK in a few days.

**Comment by hellt** [comment]
Yes, the case with deletes is something that we have improved in 23.10. I think you tested with 23.3, so worth checking with 23.10 (the on change case)

Sending deletes with sampling is something that is now being discussed in openconfig - https://github.com/openconfig/reference/pull/201

Yes, in SR Linux it is currently not possible to get a value of a list key by referencing the key directly. This is being worked on. The workaround is to subscribe/get the parent list.
