### ISSUE TITLE
Sample rate missing for Netstream

### ISSUE THREAD

**Issue by knvk** [akvorado/akvorado#841]
```
# akvorado version
akvorado v1.8.3
  Build date: 2023-04-28T17:01:57+0000
  Built with: go1.20.3
```
## Description 

Hi again, 

Currently we are testing akvorado with different switch vendors, and faced another issue, now with Huawei CE8851.
It uses netstream protocol, but if I get right, it's netflow v9 compatible. 

Akvorado parses almost all packets fields correct, except the sampling rate.

At first i thought this issue was somehow related to  #89. 
After I dumped the flow data, and noticed that sampling rate actually declared in Data flow set, in separated field with type 34 (0x22). RFC 3954 do not prohibit such behaviour.

According to [source](https://github.com/akvorado/akvorado/blob/92506280b80adebc9e7b733c74e957b9f554bf6c/inlet/flow/decoder/netflow/decode.go#L35) we are trying to detect sampling rate  in options field, if not present just use the config one.

Dump below:
[netstream-local.pcap.zip](https://github.com/akvorado/akvorado/files/12320403/netstream-local.pcap.zip)

Currently we have applied a workaround, specifying a known rate in the configuration file and have no impact.

However, we would still like to notify you that there is a problem, and would like to see a fix, if it possible.

Keep up and thanks for you work.

**Comment by vincentbernat** [comment]
Thanks. Fixed.

**Comment by aztec102** [comment]
@knvk Hello!
Can you share the ip netstream settings configuration?
