### ISSUE TITLE
console: support filtering for custom dictionaries

### ISSUE THREAD

**Issue by margau** [akvorado/akvorado#852]
With https://github.com/akvorado/akvorado/pull/840, I've added the option for custom dictionaries, creating custom dimensions. 

They are not supported in query filters (yet), which is what I wanna discuss here.

From my understanding the filtering is largely done in https://github.com/akvorado/akvorado/blob/main/console/filter/parser.peg, with the dimensions known at compile time.
As custom dict dimensions are done inside the configuration, they are only known during runtime.

I've not found a good way of doing this yet, are there ideas how we could dynamically add the custom dictionary dimensions to the parsing grammar?

**Comment by vincentbernat** [comment]
This should be possible with the PEG grammar. There is a limitation for `c.metaColumn()` as it is not able to get the name. See https://github.com/mna/pigeon/issues/105. Maybe there is another way. As for `c.acceptColumn()`, it can and it could accept any column matching a real column of the right type.

**Comment by vincentbernat** [comment]
See 9106a09bf1bc. You should be able to be more generic by having `c.acceptColumnInteger()`, `c.acceptColumnString()`, and stuff like that.

**Comment by vincentbernat** [comment]
I have pushed 2f8fdc479afe which is an improvement over 9106a09bf1bc8859784c3d3358e19de89ba46550. I didn't test anything else yet, but the idea is that instead of having:
```
ConditionUintExpr "condition on integer" ←
 column:("InIfSpeed"i !IdentStart { return c.acceptColumn() }
       / "OutIfSpeed"i !IdentStart { return c.acceptColumn() }
       / "SrcPort"i !IdentStart { return c.acceptColumn() }
       / "DstPort"i !IdentStart { return c.acceptColumn() }
       / "SrcPortNAT"i !IdentStart { return c.acceptColumn() }
       / "DstPortNAT"i !IdentStart { return c.acceptColumn() }
       / "SrcVlan"i !IdentStart { return c.acceptColumn() }
       / "DstVlan"i !IdentStart { return c.acceptColumn() }
       / "PacketSize"i !IdentStart { return c.acceptColumn() }
       / "ForwardingStatus"i !IdentStart { return c.acceptColumn() }
       / "IPTTL"i !IdentStart { return c.acceptColumn() }
       / "IPTos"i !IdentStart { return c.acceptColumn() }
       / "IPFragmentID"i !IdentStart { return c.acceptColumn() }
       / "IPFragmentOffset"i !IdentStart { return c.acceptColumn() }
       / "IPv6FlowLabel"i !IdentStart { return c.acceptColumn() }
       / "TCPFlags"i !IdentStart { return c.acceptColumn() }
       / "ICMPv4Type"i !IdentStart { return c.acceptColumn() }
       / "ICMPv4Code"i !IdentStart { return c.acceptColumn() }
       / "ICMPv6Type"i !IdentStart { return c.acceptColumn() }
       / "ICMPv6Code"i !IdentStart { return c.acceptColumn() }) _
 operator:("=" / ">=" / "<=" / "<" / ">" / "!=") _
 value:Unsigned64 {
  return []any{column, operator, value}, nil
}
```
You can have:
```
ConditionUintExpr "condition on integer" ←
 column:([a-zA-Z][a-zA-Z][0-9]+ !IdentStart { return c.acceptColumn("Uint64") }) _
 operator:("=" / ">=" / "<=" / "<" / ">" / "!=") _
 value:Unsigned64 {
  return []any{column, operator, value}, nil
}
```
Unfortunately, this would also break completion, but there may be another way.

**Comment by vincentbernat** [comment]
This is implemented in https://github.com/akvorado/akvorado/commit/6e18065be6631b019e1d8771cb9afde761238c4b.
