### ISSUE TITLE
Home graph widget filtering/configuration

### ISSUE THREAD

**Issue by margau** [akvorado/akvorado#944]
At the moment, the graph displayed at the home page is hardcoded to the data rate inbound from external interfaces ( https://github.com/akvorado/akvorado/blob/2303b579e443284808f9fa7c8195c2c16ae8b60f/console/widgets.go#L225 )

For our use case, a "total traffic" (without filtering per direction) or an option to filter for outbound traffic on external interfaces would be more relevant.
This could be done by rebuilding this query as "total flows", or with a configureable query filter portion.
Before implementing something like this, I'd like to discuss what is the best way.

I could also think of reusing the `console/graph/line`-endpoint for this, allowing all filters - which would be a more complex change however.

**Comment by vincentbernat** [comment]
I think a configurable query filter portion would work.
