### ISSUE TITLE
Sampling rate is wrong when multiple sampling rate are configured on a box

### ISSUE THREAD

**Issue by netixx** [akvorado/akvorado#997]
# Bug description

When multiple sampling rates are configured on a box (eg. Cisco NCS55 series), the rate used by akvorado may be the wrong one (dependending on paquet ordering I guess).

This is due to the fact the that SAMPLER_ID field is not used to match the correct sampler ID.
Obs-Domain is indeed 0 for both all flows so it's not enough to disambiguate.

## Steps to reproduce the problem

**Akvorado version**: 
```
# akvorado version
akvorado v1.9.1-111-g47e3d46-dirty
Built with: go1.21.3
```

Configure more that one sampling rate on the box.
```
sampler-map SPM_1OUT2000 
sampler-map SPM_1OUT2000 random 1 out-of 2000
sampler-map SPM_1OUT4000 
sampler-map SPM_1OUT4000 random 1 out-of 4000
```

And apply it on interfaces like so:
```
interface Bundle-Ether105 flow ipv4 monitor FMM_INPUT_V4 sampler SPM_1OUT2000 ingress
interface Bundle-Ether303 flow ipv4 monitor FMM_OUTPUT_V4 sampler SPM_1OUT4000 ingress
```

Here is the option frame with the two sampler
```
Cisco NetFlow/IPFIX
    Version: 9
    Count: 2
    SysUptime: 1098323.763000000 seconds
    Timestamp: Nov 30, 2023 17:16:14.000000000 CET
    FlowSequence: 2436874581
    SourceId: 0
    FlowSet 1 [id=257] (2 flows)
        FlowSet Id: (Data) (257)
        FlowSet Length: 100
        [Template Frame: 8465]
        Flow 1
            ScopeSystem: 362432d1
            SamplerID: 1
            SamplerRandomInterval: 2000
            SamplerMode: Random (2)
            SamplerName: SPM_1OUT2000
            Sampling interval: 2000
        Flow 2
            ScopeSystem: 362432d1
            SamplerID: 2
            SamplerRandomInterval: 4000
            SamplerMode: Random (2)
            SamplerName: SPM_1OUT4000
            Sampling interval: 4000
        Padding: 0000
```

## Expected outcome

Each flow should be using the `FLOW_SAMPLER_ID` field to determine the correct sampler to use for this specific flow.
```
Field (21/25): FLOW_SAMPLER_ID
Type: FLOW_SAMPLER_ID (48)
Length: 2
```

## Current outcome

One of the two sampling rate is used, leading to throughput reported as half of real throughput

Looking at the code, I think we need to add a reference to sampler ID here:
```
samplingRateSys.AddSamplingRate(10, obsDomainID, samplingRate) 
```

and match it afterwards.

**Comment by vincentbernat** [comment]
@lspgn it looks correct and it would also require some changes in GoFlow2

**Comment by netixx** [comment]
Ah right, this function is indeed in goflow2 (producer/producer_nf.go).
```
func SearchNetFlowOptionDataSets(dataFlowSet []netflow.OptionsDataFlowSet) (uint32, bool) {
	var samplingRate uint32
	var found bool
	for _, dataFlowSetItem := range dataFlowSet {
		for _, record := range dataFlowSetItem.Records {
			b := NetFlowPopulate(record.OptionsValues, 305, &samplingRate)
			if b {
				return samplingRate, b
			}
			b = NetFlowPopulate(record.OptionsValues, 50, &samplingRate)
			if b {
				return samplingRate, b
			}
			b = NetFlowPopulate(record.OptionsValues, 34, &samplingRate)
			if b {
				return samplingRate, b
			}
		}
	}
	return samplingRate, found
}
```

It would need to return a map of SamplerID to sampling rate.

**Comment by vincentbernat** [comment]
Would it be possible to share a pcap? It will be useful to avoid a future regression once this is fixed. By email if you want me to anonymize it (though it's a bit of work).

**Comment by netixx** [comment]
Yes sure, I'll work on it.

Would you like a capture of the sampler options frames, a few flows with different sampler id or both ?

**Comment by netixx** [comment]
Thanks for the quick work !!
