### ISSUE TITLE
Fail to scrape metric when there is an error decoding netflows

### ISSUE THREAD

**Issue by netixx** [akvorado/akvorado#999]
```
# akvorado version
akvorado v1.9.2-117-gc099946-dirty
  Built with: go1.21.3

Commit: c09994620a9b8a4d726d9ad7c82e76ea4043780b
```

# Bug description

akvorado may expose labels too large for prometheus to scrape (> 255 characters) when netflow decoder fails to decode.

This is due to this error printing in goflow/v2:
```
type FlowError struct {
	Version     uint16
	Type        string
	ObsDomainId uint32
	TemplateId  uint16
	Err         error
}

func (e *FlowError) Error() string {
	return fmt.Sprintf("[version:%d type:%s obsDomainId:%v: templateId:%d] %s", e.Version, e.Type, e.ObsDomainId, e.TemplateId, e.Err.Error())
} 
```

that can get too large when put into the metric label here `err.Error()`:
```
if err := netflow.DecodeMessageVersion(buf, templates, &packetNFv9, &packetIPFIX); err != nil {
		switch err.(type) {
		case *netflow.DecoderError:
			nd.metrics.errors.WithLabelValues(key, err.Error()).Inc()
		default:
			nd.metrics.errors.WithLabelValues(key, "error decoding").Inc()
		}
		return nil
	}
```

## Steps to reproduce the problem

**Akvorado version**: (first line of `akvorado version`)

Fail some netflow decoding.

## Expected outcome

Metrics collection works as expected.

## Current outcome

Prometheus fails to scrape with the following error:
```
label_value_length_limit exceeded (metric: akvorado_inlet_flow_decoder_netflow_errors_total, label name: error, value: "NetFlowV9 NetFlowV9 [version:9 type:Decode obsDoma", length: 256, limit: 255)
```

**Comment by vincentbernat** [comment]
Side question: why is it failing to decode some flows?

**Comment by netixx** [comment]
yes exactly :) :) 

I looked at the errors, and it's all "template not found", so I guess it's just until it starts up.
